{
    "annotation_task_name": "Empathy Annotation",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/empathy/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "csv", 

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
        "data_files/empathy.json"
    ],

    # Both the target and observer comments are elements in a list referenced by the "text" key.
    # See `data_files/empathy.json` for details
    "item_properties": {
        "id_key": "id",
        "text_key": "text",
    },

    # To convert the list into a string, we use `list_as_text` as shown below.
    "list_as_text": {
      "text_list_prefix_type": 'none',
    },


    "user_config": {
      "allow_all_users": True,     
      "users": [  ],
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,


    "annotation_schemes": [
        {
            "annotation_type": "likert",
            "name": "rating",
            "description": "To what extent does the observer's appraisal of the situation match that of the target speaker?",
            "min_label": "Not at all",
            "max_label": "Completely",
            "size": 5,
            "sequential_key_binding": True,
        }
    ], 

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    # you may use templates in our lib, if you want to use your own template,
    # please replace the string as a path to the template
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"

}
