site_name: potato annotation
site_url: https://github.com/davidjurgens/potato
nav:
    - Home: index.md
    - Quick Start: quick-start.md
    - Example Projects: example-projects.md
    - Usage: usage.md
    - Data Format: data_format.md
    - Schemas and Templates: schemas_and_templates.md
    - User and Collaboration: user_and_collaboration.md
    - Task Assignment: task_assignment.md
    - Productivity: productivity.md
    - Surveyflow: surveyflow.md
    - Crowdsourcing: crowdsourcing.md
    - Annotator Stats: annotator_stats.md
    - Open Sourcing: open-sourcing.md
theme: readthedocs